config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :mutants

  resources :tasks do
    collection do
      get :team_search
    end
  end

  resources :teams do
    collection do
      get :mutant_search
    end
  end

end

app/models/mutant.rb
class Mutant < ActiveRecord::Base
  has_many :team_members
  has_many :teams, :through => :team_members

  validates :name, :presence => true
  validates :name, :length => {:maximum => 30}
  validates :name, :format => {
    :with => /\A(\w|_)+\Z/,
    :message => "can only contain alphabets, numbers, and underscores(_)"
  }

  def self.search_for_team team, term, page
    exclude_ids = team ? team.mutant_ids : []
    if exclude_ids.count == 0
      mutants = where("name like '%#{term}%'").paginate(:per_page => 10, :page => page)
    else
      mutants = where("name like '%#{term}%' and id not in (?)", exclude_ids).paginate(:per_page => 10, :page => page)
    end
    mutants.collect{|mutant| {:id => mutant.id, :name => mutant.name}}
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  has_many :team_tasks
  has_many :teams, :through => :team_tasks
  accepts_nested_attributes_for :team_tasks, :allow_destroy => true

  validates :name, :presence => true
  validates :name, :length => {:maximum => 255}
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :team_tasks
  has_many :team_members
  has_many :mutants, :through => :team_members
  has_many :tasks, :through => :team_tasks
  accepts_nested_attributes_for :team_members, :allow_destroy => true

  validates :name, :presence => true
  validates :name, :length => {:maximum => 30}

  def self.search_for_task task, term, page
    exclude_ids = task ? task.team_ids : []
    if exclude_ids.count == 0
      teams = where("name like '%#{term}%'").paginate(:per_page => 10, :page => page)
    else
      teams = where("name like '%#{term}%' and id not in (?)", exclude_ids).paginate(:per_page => 10, :page => page)
    end
    teams.collect{|team| {:id => team.id, :name => team.name}}
  end
end

app/models/team_member.rb
class TeamMember < ActiveRecord::Base
  belongs_to :team
  belongs_to :mutant
end

app/models/team_task.rb
class TeamTask < ActiveRecord::Base
  belongs_to :team
  belongs_to :task
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/mutants_controller.rb
class MutantsController < ApplicationController
  def index
    @mutants = Mutant.all
  end

  def show
    @mutant = Mutant.find params[:id]
  end

  def new
    @mutant = Mutant.new
  end

  def create
    @mutant = Mutant.new mutant_params
    if @mutant.valid?
      @mutant.save
      return redirect_to(mutants_path, :notice => 'Mutant created successfully')
    else
      render :new
    end
  end

  def edit
    @mutant = Mutant.find params[:id]
  end

  def update
    @mutant = Mutant.find params[:id]
    if @mutant.update_attributes mutant_params
      return redirect_to(mutants_path, :notice => 'Mutant updated successfully')
    else
      render :edit
    end
  end

  def destroy
    @mutant = Mutant.find params[:id]
    @mutant.destroy
    return redirect_to(mutants_path, :notice => 'Mutant deleted successfully')
  end

  private

  def mutant_params
    params.require(:mutant).permit(:name)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find params[:id]
  end

  def new
    @task = Task.new
  end

  def create
    set_team_params
    @task = Task.new task_params
    if @task.valid?
      @task.save
      return redirect_to(tasks_path, :notice => 'Task created successfully')
    else
      render :new
    end
  end

  def edit
    @task = Task.find params[:id]
  end

  def update
    @task = Task.find params[:id]
    set_team_params
    if @task.update_attributes task_params
      return redirect_to(tasks_path, :notice => 'Task updated successfully')
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find params[:id]
    @task.destroy
    return redirect_to(tasks_path, :notice => 'Task deleted successfully')
  end

  def team_search
    task = params[:task_id] ? Task.find(params[:task_id]) : nil
    teams = Team.search_for_task(task, params[:q], params[:page])
    respond_to do |format|
      format.json{render :json => teams.to_json}
    end
  end

  private

  def task_params
    params.require(:task).permit(:name, :team_tasks_attributes => [:id, :team_id, :_destroy])
  end

  def set_team_params
    delete_teams = params.delete :delete_teams
    new_teams    = params.delete :new_teams

    params[:task][:team_tasks_attributes] = []

    if delete_teams
      delete_teams.each{|t| params[:task][:team_tasks_attributes] << {:id => t, :_destroy => true}}
    end
    if new_teams.length > 0
      new_teams.split(",").each{|t| params[:task][:team_tasks_attributes] << {:team_id => t}}
    end
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all
  end

  def show
    @team = Team.find params[:id]
  end

  def new
    @team = Team.new
  end

  def create
    set_team_member_params
    @team = Team.new team_params
    if @team.valid?
      @team.save
      return redirect_to(teams_path, :notice => 'Team created successfully')
    else
      render :new
    end
  end

  def edit
    @team = Team.find params[:id]
  end

  def update
    @team = Team.find params[:id]
    set_team_member_params

    if @team.update_attributes team_params
      return redirect_to(teams_path, :notice => 'Team updated successfully')
    else
      render :edit
    end
  end

  def destroy
    @team = Team.find params[:id]
    @team.destroy
    return redirect_to(teams_path, :notice => 'Team deleted successfully')
  end

  def mutant_search
    team = params[:team_id] ? Team.find(params[:team_id]) : nil
    mutants = Mutant.search_for_team(team, params[:q], params[:page])
    respond_to do |format|
      format.json{render :json => mutants.to_json}
    end
  end

  private

  def team_params
    params.require(:team).permit(:name, :team_members_attributes => [:id, :mutant_id, :_destroy])
  end

  def set_team_member_params
    delete_mutants = params.delete :delete_mutants
    new_mutants    = params.delete :new_mutants

    params[:team][:team_members_attributes] = []

    if delete_mutants
      delete_mutants.each{|m| params[:team][:team_members_attributes] << {:id => m, :_destroy => true}}
    end
    if new_mutants.length > 0
      new_mutants.split(",").each{|m| params[:team][:team_members_attributes] << {:mutant_id => m}}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def xmen_autocomplete_field name, placeholder, url, key
    text_field_tag name, nil, :class => 'xmen-fetch', :data => {:placeholder => placeholder, :url => url, :key => key }
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mutants_helper.rb
module MutantsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/home/index.html.erb
<h2>Welcome to Professor X's Lab!</h2>
<div>
  <%= link_to 'Manage Tasks', tasks_path %>
</div>
<div>
  <%= link_to 'Manage Teams', teams_path %>
</div>
<div>
  <%= link_to 'Manage Mutants', mutants_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Professor X's Westchester Mansion</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <style>
      #header {
        margin-bottom: 20px;
      }
    </style>
  </head>
  <body>
    <div id="header">
      <%= render :partial => 'shared/header' %>
    </div>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/mutants/_form.html.erb
<% if @mutant.errors.any? %>
  <div class="error_messages">
    <h2><%= pluralize(@mutant.errors.count, "error") %> prohibited this mutant from being saved:</h2>
    <ul>
      <% @mutant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @mutant do |form| %>
  <table>
    <tr>
      <td>Name</td>
      <td><%= form.text_field :name, :placeholder => "mutant name" %></td>
    </tr>
    <tr>
      <td></td>
      <td><%= form.submit %></td>
    </tr>
  </table>
<% end %>

app/views/mutants/_teams.html.erb
<% if mutant.teams.count > 0 %>
  <div><strong>This mutant belongs to following teams</strong></div>
  <table>
    <% mutant.teams.each do |team| %>
      <tr>
        <td><%= link_to team.name, team_path(team) %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  This mutant belongs to no team
<% end %>

app/views/mutants/edit.html.erb
<h2>Edit Mutant</h2>
<%= render :partial => 'form' %>

app/views/mutants/index.html.erb
<table>
<% @mutants.each do |mutant| %>
  <tr>
    <td><%= mutant.name %></td>
    <td><%= link_to "Edit", edit_mutant_path(mutant.id) %></td>
    <td><%= link_to "Delete", mutant_path(mutant.id), :method => 'DELETE' %></td>
    <td><%= link_to "Details", mutant_path(mutant.id) %></td>
  </tr>
<% end %>
</table>

<div>
  <strong><%= link_to "Create Mutant", new_mutant_path %></strong>
</div>

app/views/mutants/new.html.erb
<h2>New Mutant</h2>
<%= render :partial => 'form' %>

app/views/mutants/show.html.erb
<h2>
  <%= @mutant.name %>
</h2>
<%= render :partial => 'teams', :locals => {:mutant => @mutant} %>

app/views/shared/_header.html.erb
<table>
  <tr>
    <td><%= link_to "Lab", root_path %></td>
    <td><%= link_to "Tasks", tasks_path %></td>
    <td><%= link_to "Teams", teams_path %></td>
    <td><%= link_to "Mutants", mutants_path %></td>
  </tr>
</table>

app/views/tasks/_form.html.erb
<% if @task.errors.any? %>
  <div class="error_messages">
    <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
    <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @task do |form| %>
  <table>
    <tr>
      <td>Name</td>
      <td><%= form.text_field :name, :placeholder => "task name" %></td>
    </tr>
    <% if @task.team_tasks.count > 0 %>
      <tr>
        <td><strong>Teams Assigned</strong></td>
        <td></td>
      </tr>
    <% end %>
    <% @task.team_tasks.each do |team_task| %>
      <tr>
        <td><%= team_task.team.name %></td>
        <td><small>Remove</small> <input type='checkbox' name='delete_teams[]' value='<%= team_task.id %>' /></td>
      </tr>
    <% end %>
    <tr>
      <td>More Teams</td>
      <td><%= xmen_autocomplete_field 'new_teams', "Search Team", team_search_tasks_path(:task_id => @task.id, :format => 'json'), 'name' %></td>
    </tr>
    <tr>
      <td></td>
      <td><%= form.submit %></td>
    </tr>
  </table>
<% end %>

app/views/tasks/_teams.html.erb
<% if task.teams.count > 0 %>
  <div><strong>Teams working on this task</strong></div>
  <table>
    <% task.teams.each do |team| %>
      <tr>
        <td><%= link_to team.name, team_path(team) %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  No teams working on this task yet.
<% end %>

app/views/tasks/edit.html.erb
<h2>Edit Task</h2>
<%= render :partial => 'form' %>

app/views/tasks/index.html.erb
<table>
<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td><%= link_to "Assign Teams", edit_task_path(task.id) %></td>
    <td><%= link_to "Delete", task_path(task.id), :method => 'DELETE' %></td>
    <td><%= link_to "Details", task_path(task.id) %></td>
  </tr>
<% end %>
</table>

<div>
  <strong><%= link_to "Create Task", new_task_path %></strong>
</div>

app/views/tasks/new.html.erb
<h2>New Task</h2>
<%= render :partial => 'form' %>

app/views/tasks/show.html.erb
<h2>
  <%= @task.name %>
</h2>
<%= render :partial => 'teams', :locals => {:task => @task} %>